name: "Build&Deploy ros-master images"

on:
  # Trigger the workflow on push or pull request
  # but only for the main branch
  # or on tag of type v*.*.*
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
  release:
    types: [released]
jobs:
  ros-master-melodic:
    uses: MOV-AI/.github/.github/workflows/docker-workflow.yml@main
    with:
      docker_file: melodic/Dockerfile
      docker_image: devops/ros-master-melodic
      public: true
      public_image: ce/ros-master-melodic
      github_ref: ${{ github.ref }}
    secrets:
      registry_user: ${{ secrets.PORTUS_APP_USER }}
      registry_password: ${{ secrets.PORTUS_APP_TOKEN }}
  ros-master-noetic:
    uses: MOV-AI/.github/.github/workflows/docker-workflow.yml@main
    with:
      docker_file: noetic/Dockerfile
      docker_image: devops/ros-master-noetic
      public: true
      public_image: ce/ros-master-noetic
      github_ref: ${{ github.ref }}
    secrets:
      registry_user: ${{ secrets.PORTUS_APP_USER }}
      registry_password: ${{ secrets.PORTUS_APP_TOKEN }}
