name: "Deploy to Docker Registry"

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  DeployMelodic:
    env:
      PUSH_TO_REGISTRY: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Hadolint melodic
        uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: melodic/Dockerfile
          format: tty
          failure-threshold: error # optional, default is info
          # A space separated string of rules to ignore
          ignore: # optional
          # Path to a config file
          config: # optional

      - name: Login to Movai Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.PORTUS_APP_USER }}
          password: ${{ secrets.PORTUS_APP_TOKEN }}
          registry: registry.cloud.mov.ai

      - name: Build and push melodic
        uses: docker/build-push-action@v2
        with:
          context: .
          file: melodic/Dockerfile
          push: ${env.PUSH_TO_REGISTRY}
          tags: registry.cloud.mov.ai/develop/ros-master:melodic
          build-args:

  DeployNoetic:
    env:
      PUSH_TO_REGISTRY: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Hadolint noetic
        uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: noetic/Dockerfile
          format: tty
          failure-threshold: error # optional, default is info
          # A space separated string of rules to ignore
          ignore: # optional
          # Path to a config file
          config: # optional

      - name: Login to Movai Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.PORTUS_APP_USER }}
          password: ${{ secrets.PORTUS_APP_TOKEN }}
          registry: registry.cloud.mov.ai

      - name: Build and push noetic
        uses: docker/build-push-action@v2
        with:
          context: .
          file: noetic/Dockerfile
          push: ${env.PUSH_TO_REGISTRY}
          tags: registry.cloud.mov.ai/develop/ros-master:noetic
          build-args:
